# ----------------------------------------------------------------------------------------------
# CloudWatch Log Group for Lambda.
# ----------------------------------------------------------------------------------------------
resource "aws_cloudwatch_log_group" "lambda" {
  name              = "/aws/lambda/${local.lambda_function_name}"
  retention_in_days = 30
}

# ----------------------------------------------------------------------------------------------
# Dummy Lambda artifact generated by Terraform.
# ----------------------------------------------------------------------------------------------
data "archive_file" "lambda_dummy" {
  type        = "zip"
  source_dir  = "${path.module}/dummy"
  output_path = "${path.module}/.terraform/dummy.zip"
}

# ----------------------------------------------------------------------------------------------
# Lambda function (uses Terraform-generated dummy artifact).
# ----------------------------------------------------------------------------------------------
resource "aws_lambda_function" "api" {
  function_name = local.lambda_function_name
  role          = aws_iam_role.lambda.arn
  runtime       = "nodejs22.x"
  handler       = "index.handler"

  filename         = data.archive_file.lambda_dummy.output_path
  source_code_hash = data.archive_file.lambda_dummy.output_base64sha256

  lifecycle {
    ignore_changes = [source_code_hash]
  }

  timeout     = 30
  memory_size = 1024

  environment {
    variables = {
      FILES_BUCKET_NAME = aws_s3_bucket.files.bucket

      TABLE_SUBJECTS           = aws_dynamodb_table.subjects.name
      TABLE_TESTS              = aws_dynamodb_table.tests.name
      TABLE_QUESTIONS          = aws_dynamodb_table.questions.name
      TABLE_ATTEMPTS           = aws_dynamodb_table.attempts.name
      TABLE_GRADED_SHEETS      = aws_dynamodb_table.graded_sheets.name
      TABLE_WORDS              = aws_dynamodb_table.words.name
      TABLE_WORD_GROUPS        = aws_dynamodb_table.word_groups.name
      TABLE_WORD_TESTS         = aws_dynamodb_table.word_tests.name
      TABLE_WORD_TEST_ATTEMPTS = aws_dynamodb_table.word_test_attempts.name
      TABLE_REVIEW_TESTS       = aws_dynamodb_table.review_tests.name
      TABLE_REVIEW_TEST_ITEMS  = aws_dynamodb_table.review_test_items.name
      TABLE_REVIEW_LOCKS       = aws_dynamodb_table.review_locks.name
      TABLE_REVIEW_ATTEMPTS    = aws_dynamodb_table.review_attempts.name
      TABLE_EXAM_PAPERS        = aws_dynamodb_table.exam_papers.name
      TABLE_EXAM_RESULTS       = aws_dynamodb_table.exam_results.name
      BEDROCK_REGION           = "us-east-1"
    }
  }

  depends_on = [aws_cloudwatch_log_group.lambda]
}

# ----------------------------------------------------------------------------------------------
# CloudWatch Log Group for Bedrock Lambda.
# ----------------------------------------------------------------------------------------------
resource "aws_cloudwatch_log_group" "bedrock" {
  name              = "/aws/lambda/${local.bedrock_function_name}"
  retention_in_days = 30
}

# ----------------------------------------------------------------------------------------------
# Bedrock Lambda function.
# ----------------------------------------------------------------------------------------------
resource "aws_lambda_function" "bedrock" {
  function_name = local.bedrock_function_name
  role          = aws_iam_role.lambda.arn
  runtime       = "nodejs22.x"
  handler       = "handlers/bedrock.handler"

  filename         = data.archive_file.lambda_dummy.output_path
  source_code_hash = data.archive_file.lambda_dummy.output_base64sha256

  lifecycle {
    ignore_changes = [source_code_hash]
  }

  timeout     = 300
  memory_size = 1024

  environment {
    variables = {
      FILES_BUCKET_NAME = aws_s3_bucket.files.bucket

      TABLE_SUBJECTS           = aws_dynamodb_table.subjects.name
      TABLE_TESTS              = aws_dynamodb_table.tests.name
      TABLE_QUESTIONS          = aws_dynamodb_table.questions.name
      TABLE_ATTEMPTS           = aws_dynamodb_table.attempts.name
      TABLE_GRADED_SHEETS      = aws_dynamodb_table.graded_sheets.name
      TABLE_WORDS              = aws_dynamodb_table.words.name
      TABLE_WORD_GROUPS        = aws_dynamodb_table.word_groups.name
      TABLE_WORD_TESTS         = aws_dynamodb_table.word_tests.name
      TABLE_WORD_TEST_ATTEMPTS = aws_dynamodb_table.word_test_attempts.name
      TABLE_REVIEW_TESTS       = aws_dynamodb_table.review_tests.name
      TABLE_REVIEW_TEST_ITEMS  = aws_dynamodb_table.review_test_items.name
      TABLE_REVIEW_LOCKS       = aws_dynamodb_table.review_locks.name
      TABLE_REVIEW_ATTEMPTS    = aws_dynamodb_table.review_attempts.name
      TABLE_EXAM_PAPERS        = aws_dynamodb_table.exam_papers.name
      TABLE_EXAM_RESULTS       = aws_dynamodb_table.exam_results.name
    }
  }

  depends_on = [aws_cloudwatch_log_group.bedrock]
}
