# ----------------------------------------------------------------------------------------------
# CloudWatch Log Group for Lambda.
# ----------------------------------------------------------------------------------------------
resource "aws_cloudwatch_log_group" "lambda" {
  name              = "/aws/lambda/${var.lambda_function_name}"
  retention_in_days = 30
}

# ----------------------------------------------------------------------------------------------
# Dummy Lambda artifact generated by Terraform.
# ----------------------------------------------------------------------------------------------
data "archive_file" "lambda_dummy" {
  type        = "zip"
  source_dir  = "${path.module}/lambda_dummy"
  output_path = "${path.module}/.terraform/lambda_dummy.zip"
}

# ----------------------------------------------------------------------------------------------
# Lambda function (uses Terraform-generated dummy artifact).
# ----------------------------------------------------------------------------------------------
resource "aws_lambda_function" "api" {
  function_name = var.lambda_function_name
  role          = aws_iam_role.lambda.arn
  runtime       = "nodejs20.x"
  handler       = "index.handler"

  filename         = data.archive_file.lambda_dummy.output_path
  source_code_hash = data.archive_file.lambda_dummy.output_base64sha256

  timeout     = 30
  memory_size = 1024

  environment {
    variables = {
      AWS_REGION = data.aws_region.current.name

      COGNITO_USER_POOL_ID  = aws_cognito_user_pool.auth.id
      COGNITO_APP_CLIENT_ID = aws_cognito_user_pool_client.auth.id

      FILES_BUCKET_NAME = aws_s3_bucket.files.bucket

      SUBJECTS_TABLE           = aws_dynamodb_table.subjects.name
      TESTS_TABLE              = aws_dynamodb_table.tests.name
      QUESTIONS_TABLE          = aws_dynamodb_table.questions.name
      ATTEMPTS_TABLE           = aws_dynamodb_table.attempts.name
      ANSWER_SHEETS_TABLE      = aws_dynamodb_table.answer_sheets.name
      GRADED_SHEETS_TABLE      = aws_dynamodb_table.graded_sheets.name
      WORDS_TABLE              = aws_dynamodb_table.words.name
      WORD_TESTS_TABLE         = aws_dynamodb_table.word_tests.name
      WORD_TEST_ATTEMPTS_TABLE = aws_dynamodb_table.word_test_attempts.name
    }
  }

  depends_on = [aws_cloudwatch_log_group.lambda]
}
