export { AttemptsRepository } from './attemptRepository';
export { BedrockRepository } from './bedrockRepository';
export { DashboardRepository } from './dashboardRepository';
export { ExamPapersRepository, ExamResultsRepository } from './examRepository';
export { KanjiRepository } from './kanjiRepository';
export { MaterialRepository } from './materialRepository';
export { QuestionRepository } from './questionRepository';
export { ReviewTestRepository } from './reviewTestRepository';
export { WordIncorrectRepository } from './wordIncorrectRepository';
export { WordTestAttemptRepository } from './wordTestAttemptRepository';
